name: CI learning

on:
  push:
     branches: ["main"]

job:
  build:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Code
       uses: action/Checkout@v4

     - name: print message
       uses: echo "Hello, CI/CD"

     - name: run script
       run: |
          echo "Running script..."
          ls -la




